Feature/plausible analytics new
normative/dtpr-stickers pull request #51
Opened 2021-11-02 20:43 UTC by julia-rom

Created a new PR as per Anthony's comment for the previous one:

> the issue w/ the plausible branch is the buildpack migration has been merged into the plausible branch but buildpacks are only automatically provisioned on app creation. Options are to close/open a new PR so that a new review app is created, or manually replace nodejs with the create-react-app buildpack and redeploy

2021-11-03 14:39 UTC, tonybennett commented
Per last PR, code looks good, just need @turnKei to validate everything is coming through correctly now that the url is working

2021-11-03 21:13 UTC, turnKei commented on public/index.html
> +    <script defer data-domain="%REACT_APP_DOMAIN_URL%,%REACT_APP_AGGREGATED_DOMAIN_URL%"src="https://plausible.io/js/plausible.local.js"></script>
This is still pointing to local, so won't work when deployed. As discussed this should be changed to `https://plausible.io/js/plausible.js`

2021-11-03 21:19 UTC, turnKei requested changes
still pointing to local env, should be the standard per plausible docs

2021-11-04 14:52 UTC, turnKei commented
Not showing up in Plausible, looks like you forgot to add those config vars to the review app?

2021-11-04 20:46 UTC, turnKei approved these changes

2021-11-04 20:47 UTC, merged